version: "3"
services:
  dev:
    user: vscode

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached
      # Preserve VSCode Extensions
      - vscode_extension:/home/vscode/.vscode-server/extensions
      - vscode_insider_extension:/home/vscode/.vscode-server-insiders/extensions
      # mount Github Cli config dir
      - ~/.config/gh:/home/vscode/.config/gh:cached
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    links:
      - redis
    
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  redis:
    image: redis:6.0.6-buster
    volumes:
      - redisdata:/data
    hostname: redis

  postgres:
    build: 
      context: ../
      dockerfile: build/metricsdb/Dockerfile
    volumes:
      - psqldata:/var/lib/postgresql/data/pgdata
    environment: 
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=supersecret
    hostname: postgres

volumes:
  redisdata: {}
  psqldata: {}
  vscode_extension:
  vscode_insider_extension:
